// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package pgdb

import (
	"context"
	"time"
)

const allBookmarks = `-- name: AllBookmarks :many
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks ORDER BY created_at DESC
`

func (q *Queries) AllBookmarks(ctx context.Context) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, allBookmarks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.ThumbnailUrl,
			&i.ShaarliShortUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookmarksOverTime = `-- name: BookmarksOverTime :many
SELECT DATE(created_at)::text AS date, COUNT(*)::bigint AS count
FROM bookmarks
WHERE created_at >= $1
GROUP BY date ORDER BY date
`

type BookmarksOverTimeRow struct {
	Date  string `json:"date"`
	Count int64  `json:"count"`
}

func (q *Queries) BookmarksOverTime(ctx context.Context, createdAt time.Time) ([]BookmarksOverTimeRow, error) {
	rows, err := q.db.QueryContext(ctx, bookmarksOverTime, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookmarksOverTimeRow{}
	for rows.Next() {
		var i BookmarksOverTimeRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBookmarks = `-- name: CountBookmarks :one
SELECT COUNT(*) FROM bookmarks
`

func (q *Queries) CountBookmarks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookmarks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookmarksSince = `-- name: CountBookmarksSince :one
SELECT COUNT(*) FROM bookmarks WHERE created_at >= $1
`

func (q *Queries) CountBookmarksSince(ctx context.Context, createdAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBookmarksSince, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
`

type CreateBookmarkParams struct {
	ShortUrl        string    `json:"short_url"`
	Url             string    `json:"url"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	ThumbnailUrl    string    `json:"thumbnail_url"`
	ShaarliShortUrl string    `json:"shaarli_short_url"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.ShortUrl,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
		arg.ShaarliShortUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.ShaarliShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllBookmarks = `-- name: DeleteAllBookmarks :execrows
DELETE FROM bookmarks
`

func (q *Queries) DeleteAllBookmarks(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllBookmarks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE id = $1
`

func (q *Queries) DeleteBookmark(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBookmark, id)
	return err
}

const getBookmarkByID = `-- name: GetBookmarkByID :one
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks WHERE id = $1
`

func (q *Queries) GetBookmarkByID(ctx context.Context, id int64) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByID, id)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.ShaarliShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookmarkByShaarliHash = `-- name: GetBookmarkByShaarliHash :one
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks WHERE shaarli_short_url = $1
`

func (q *Queries) GetBookmarkByShaarliHash(ctx context.Context, shaarliShortUrl string) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByShaarliHash, shaarliShortUrl)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.ShaarliShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookmarkByShortURL = `-- name: GetBookmarkByShortURL :one
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks WHERE short_url = $1
`

func (q *Queries) GetBookmarkByShortURL(ctx context.Context, shortUrl string) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByShortURL, shortUrl)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.ShaarliShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookmarkByURL = `-- name: GetBookmarkByURL :one
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks WHERE url = $1
`

func (q *Queries) GetBookmarkByURL(ctx context.Context, url string) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, getBookmarkByURL, url)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.ShaarliShortUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookmarkIgnore = `-- name: InsertBookmarkIgnore :execrows
INSERT INTO bookmarks (short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (url) DO NOTHING
`

type InsertBookmarkIgnoreParams struct {
	ShortUrl        string    `json:"short_url"`
	Url             string    `json:"url"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	ThumbnailUrl    string    `json:"thumbnail_url"`
	ShaarliShortUrl string    `json:"shaarli_short_url"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) InsertBookmarkIgnore(ctx context.Context, arg InsertBookmarkIgnoreParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertBookmarkIgnore,
		arg.ShortUrl,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
		arg.ShaarliShortUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListBookmarksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, listBookmarks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.ThumbnailUrl,
			&i.ShaarliShortUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentBookmarks = `-- name: RecentBookmarks :many
SELECT id, short_url, url, title, description, thumbnail_url, shaarli_short_url, created_at, updated_at
FROM bookmarks ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) RecentBookmarks(ctx context.Context, limit int32) ([]Bookmark, error) {
	rows, err := q.db.QueryContext(ctx, recentBookmarks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bookmark{}
	for rows.Next() {
		var i Bookmark
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.ThumbnailUrl,
			&i.ShaarliShortUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shortURLExists = `-- name: ShortURLExists :one
SELECT EXISTS(SELECT 1 FROM bookmarks WHERE short_url = $1)
`

func (q *Queries) ShortURLExists(ctx context.Context, shortUrl string) (bool, error) {
	row := q.db.QueryRowContext(ctx, shortURLExists, shortUrl)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const topDomains = `-- name: TopDomains :many
SELECT
    regexp_replace(substring(url from '://([^/]+)'), '^www\.', '') AS domain,
    COUNT(*)::bigint AS count
FROM bookmarks
WHERE created_at >= $1
GROUP BY domain ORDER BY count DESC LIMIT $2
`

type TopDomainsParams struct {
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

type TopDomainsRow struct {
	Domain string `json:"domain"`
	Count  int64  `json:"count"`
}

func (q *Queries) TopDomains(ctx context.Context, arg TopDomainsParams) ([]TopDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, topDomains, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopDomainsRow{}
	for rows.Next() {
		var i TopDomainsRow
		if err := rows.Scan(&i.Domain, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookmark = `-- name: UpdateBookmark :exec
UPDATE bookmarks
SET url = $1, title = $2, description = $3, thumbnail_url = $4, shaarli_short_url = $5, updated_at = $6
WHERE id = $7
`

type UpdateBookmarkParams struct {
	Url             string    `json:"url"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	ThumbnailUrl    string    `json:"thumbnail_url"`
	ShaarliShortUrl string    `json:"shaarli_short_url"`
	UpdatedAt       time.Time `json:"updated_at"`
	ID              int64     `json:"id"`
}

func (q *Queries) UpdateBookmark(ctx context.Context, arg UpdateBookmarkParams) error {
	_, err := q.db.ExecContext(ctx, updateBookmark,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
		arg.ShaarliShortUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
